apiVersion: v1
kind: Service
metadata:
  name: ebuy-product-service
spec:
  type: NodePort
  selector:
    app: ebuy-product-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086
