apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebuy-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebuy-product-service
  template:
    metadata:
      labels:
        app: ebuy-product-service
    spec:
      containers:
        - name: ebuy-product-service
          image: ebuy-product-service-ebuy-product-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/product_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: dev
